insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (1'Alzarri Joseph', 8, 'West Indies', 4);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (2'Ben Stokes', 8, 'England', 2);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (3'Chemar Holder ', 8, 'West Indies', 4);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (4'Chris Woakes', 8, 'England', 2);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (5'Dom Bess', 8, 'England', 4);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (6'Dom Sibley', 8, 'England', 1);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (7'James Anderson', 8, 'England', 4);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (8'Jason Holder', 8, 'West Indies', 2);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (9'Jermaine Blackwood', 8, 'West Indies', 1);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (10'Joe Denly', 8, 'England', 1);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (11'Jofra Archer', 8, 'England', 2);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (12'John Campbell', 8, 'West Indies', 1);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (13'Jos Buttler', 8, 'England', 3);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (14'Kemar Roach', 8, 'West Indies', 4);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (15'Kraigg Brathwaite', 8, 'West Indies', 1);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (16'Mark Wood', 8, 'England', 4);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (17'Nkrumah Bonner', 8, 'West Indies', 3);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (18'Ollie Pope', 8, 'England', 1);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (19'Rahkeem Cornwall', 8, 'West Indies', 2);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (20'Raymon Reifer', 8, 'West Indies', 2);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (21'Rory Burns', 8, 'England', 1);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (22'Roston Chase', 8, 'West Indies', 2);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (23'Shai Hope', 8, 'West Indies', 3);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (24'Shamarh Brooks', 8, 'West Indies', 1);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (25'Shane Dowrich', 8, 'West Indies', 2);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (26'Shannon Gabriel', 8, 'West Indies', 4);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (27'Stuart Broad', 8, 'England', 4);
insert into cricketf4u_players (id,  playerName, playerSalary, playerTeam, playerPosition_id) Values (28'Zak Crawley', 8, 'England', 1);
